services:
  admin-client:
    image: ${ADMIN_CLIENT_IMAGE:-ghcr.io/al-madhrasathul-arabiyyathul-islamiyya/bell-system/admin:latest}
    pull_policy: always
    container_name: bell-system-admin-client
    ports:
      - "8081:80"
    restart: unless-stopped
