services:
  backend:
    image: ${BACKEND_IMAGE:-ghcr.io/al-madhrasathul-arabiyyathul-islamiyya/bell-system/backend:latest}
    pull_policy: always
    container_name: bell-system-backend
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "8080:8080"
    restart: unless-stopped
    volumes:
      - ./config.docker.toml:/app/config/config.toml:ro
      - ./api:/app/api:ro
      - ./data/audio:/app/data/audio
